README.mdを現状に合わせて更新する
yojo-art/.github pull request #2
Opened 2024-10-31 17:58 UTC by kozakura913

メンバー紹介文に誤りがあればレビュー書いて

2024-11-01 05:31 UTC, jj1guj approved these changes

2024-11-01 07:08 UTC, natumi-kaoru requested changes

2024-11-01 07:08 UTC, natumi-kaoru commented on profile/README.md
> +|夏見かおる|<img src="https://github.com/yojo-art/cherrypick/assets/121443048/87a2d9ba-2b99-46a9-bf52-73cb7521b3ec" width="256">  |~~某個人情報の透明性を特徴としたサーバーに住む~~分散したカラオケ好きの~~おねえちゃん~~絵描きさん。</br>幼女.Artに含まれる数少ない
> 某個人情報の透明性を特徴としたサーバーに住む
TKNGHにはもう住んでない（閉鎖済）のでここは削除お願いします。

2024-11-01 15:36 UTC, penginn-net requested changes

2024-11-01 15:36 UTC, penginn-net commented on profile/README.md
> +|JJ1GUJ|<img src="/assets/icons/jj1guj.webp" width="256">|将棋AIとかオセロAI作ってる。</br>ロリコンではないらしい</br>自宅サーバーはRaspberryPi  |モデレーション</br>コードレビュー|
画像で404出てる

2024-11-01 15:36 UTC, penginn-net commented on profile/README.md
> +|ぺん|<img src="/assets/icons/2024-01-23%2018-52-45%201.png.webp" width="256">|常にえっちなことを考えてるペンギン。</br>幼女.artの管理者兼インフラ担当。</br>自宅サーバーはExpress5800とPRIMERGY|プロジェクトリーダー(←！？)</br>インスタンス管理者</br>サーバーインフラ担当</br
```suggestion
|ぺん|<img src="/assets/icons/2024-01-23%2018-52-45%201.png.webp" width="256">|常にえっちなことを考えてるペンギン。</br>幼女.artの管理者兼インフラ担当。</br>自宅サーバーはExpress5800とPRIMERGY|</br>インスタンス共同管理者</br>サーバーインフラ担当</br>メインロリコントリビューター|
```

2024-11-01 15:37 UTC, penginn-net commented on profile/README.md
> +|JJ1GUJ|<img src="/assets/icons/jj1guj.webp" width="256">|将棋AIとかオセロAI作ってる。</br>ロリコンではないらしい</br>自宅サーバーはRaspberryPi  |モデレーション</br>コードレビュー|
mainブランチにあったのね

2024-11-01 15:38 UTC, kozakura913 commented on profile/README.md
> +|JJ1GUJ|<img src="/assets/icons/jj1guj.webp" width="256">|将棋AIとかオセロAI作ってる。</br>ロリコンではないらしい</br>自宅サーバーはRaspberryPi  |モデレーション</br>コードレビュー|
mainブランチには入ってるからマージしたらある

2024-11-03 09:54 UTC, natumi-kaoru approved these changes

2024-11-03 19:03 UTC, kozakura913 commented on profile/README.md
> +|ぺん|<img src="/assets/icons/2024-01-23%2018-52-45%201.png.webp" width="256">|常にえっちなことを考えてるペンギン。</br>幼女.artの管理者兼インフラ担当。</br>自宅サーバーはExpress5800とPRIMERGY|プロジェクトリーダー(←！？)</br>インスタンス管理者</br>サーバーインフラ担当</br
あなたがプロジェクトリーダーです
逃さないよ

2024-11-06 10:13 UTC, penginn-net approved these changes

2024-11-06 10:16 UTC, merged